--- #YAML:1.0
name:                Catalyst-Plugin-Acme-LOLCAT
version:             0.01
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Acme::LOLCAT:                  0
    Catalyst:                      5.6
    HTML::TokeParser:              2
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ashley Pond V <ashley@cpan.org>
